// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// quadFormByRow
SEXP quadFormByRow(const Eigen::MappedSparseMatrix< double > S, const Eigen::MappedSparseMatrix< double > X);
RcppExport SEXP _moretrees_quadFormByRow(SEXP SSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix< double > >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix< double > >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(quadFormByRow(S, X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_moretrees_quadFormByRow", (DL_FUNC) &_moretrees_quadFormByRow, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_moretrees(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
